export const items = [
  {
    id: 1,
    itemName: 'airpods',
    itemPrice: 100000,
    itemImage: require('../../assets/test/airpods.jpeg'),
    itemCondition: 'B',
    itemLocation: 'Seoul',
    itemUploader: 'admin',
    itemDescription: 'apple airpods pro',
  },
  {
    id: 2,
    itemName: 'iphone',
    itemPrice: 1000000,
    itemImage: require('../../assets/test/iphone.jpeg'),
    itemCondition: 'A',
    itemLocation: 'Busan',
    itemUploader: 'admin',
    itemDescription: 'apple iphone 12 pro max',
  },
  {
    id: 3,
    itemName: 'macbook',
    itemPrice: 2000000,
    itemImage: require('../../assets/test/macbook.jpeg'),
    itemCondition: 'A',
    itemLocation: 'Incheon',
    itemUploader: 'admin',
    itemDescription: 'apple macbook pro',
  },
  {
    id: 4,
    itemName: 'apple watch',
    itemPrice: 500000,
    itemImage: require('../../assets/test/watch.jpeg'),
    itemCondition: 'B',
    itemLocation: 'Daegu',
    itemUploader: 'admin',
    itemDescription: 'apple watch series 6',
  },
  {
    id: 5,
    itemName: 'ipad',
    itemPrice: 800000,
    itemImage: require('../../assets/test/ipad1.jpeg'),
    itemCondition: 'A',
    itemLocation: 'Daejeon',
    itemUploader: 'admin',
    itemDescription: 'apple ipad pro',
  },
  {
    id: 6,
    itemName: 'mac mini',
    itemPrice: 1000000,
    itemImage: require('../../assets/test/macmini.jpeg'),
    itemCondition: 'B',
    itemLocation: 'Ulsan',
    itemUploader: 'admin',
    itemDescription: 'apple mac mini',
  },

  {
    id: 7,
    itemName: 'imac',
    itemPrice: 10000000,
    itemImage: require('../../assets/test/imac.jpeg'),
    itemCondition: 'A',
    itemLocation: 'Gwangju',
    itemUploader: 'admin',
    itemDescription: 'apple imac',
  },
]
